# Generated by Django 3.1.3 on 2021-02-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('price_limit', models.FloatField()),
                ('product', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('new_price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('href', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.URLField(max_length=100)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.article')),
            ],
        ),
    ]
