# Generated by Django 3.1.3 on 2021-03-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210303_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
